#ifndef PINS_H
#define PINS_H

#define RELAY_1_PORT    GPIOC
#define RELAY_1_PIN     LL_GPIO_PIN_6
#define RELAY_1_CLOCK   LL_AHB1_GRP1_PERIPH_GPIOC

#define RELAY_2_PORT    GPIOC
#define RELAY_2_PIN     LL_GPIO_PIN_7
#define RELAY_2_CLOCK   LL_AHB1_GRP1_PERIPH_GPIOC

#define RELAY_3_PORT    GPIOC
#define RELAY_3_PIN     LL_GPIO_PIN_8
#define RELAY_3_CLOCK   LL_AHB1_GRP1_PERIPH_GPIOC

#define EXTENDER_PINS_PORT  GPIOB
#define EXTENDER_RX_PIN LL_GPIO_PIN_7
#define EXTENDER_TX_PIN LL_GPIO_PIN_6
#define EXTENDER_PINS_CLOCK  LL_AHB1_GRP1_PERIPH_GPIOB
#define EXTENDER_UART_CLOCK LL_APB1_GRP2_PERIPH_USART1
#define EXTENDER_UART   USART1
//#define EXTENDER_SPEED  57600
#define EXTENDER_SPEED  230400
#define EXTENDER_AF     LL_GPIO_AF_0
#define EXTENDER_RTS_PORT   GPIOA
#define EXTENDER_RTS_PIN    LL_GPIO_PIN_12
#define EXTENDER_RTS_CLOCK  LL_AHB1_GRP1_PERIPH_GPIOA

#define PERIPHERAL_POWER_SWITCH_CLOCK   LL_AHB1_GRP1_PERIPH_GPIOC
#define PERIPHERAL_POWER_SWITCH_PIN     LL_GPIO_PIN_10
#define PERIPHERAL_POWER_SWITCH_PORT    GPIOC

#define PMU1_PINS_PORT GPIOA
#define PMU1_RX_PIN    LL_GPIO_PIN_1
#define PMU1_TX_PIN    LL_GPIO_PIN_0
#define PMU1_PINS_CLOCK    LL_AHB1_GRP1_PERIPH_GPIOA
#define PMU1_UART_CLOCK    LL_APB1_GRP1_PERIPH_USART4
#define PMU1_UART      USART4
#define PMU1_SPEED     9600
#define PMU1_AF        LL_GPIO_AF_4

#define PMU2_PINS_PORT GPIOC
#define PMU2_RX_PIN    LL_GPIO_PIN_5
#define PMU2_TX_PIN    LL_GPIO_PIN_4
#define PMU2_PINS_CLOCK    LL_AHB1_GRP1_PERIPH_GPIOC
#define PMU2_UART_CLOCK    LL_APB1_GRP1_PERIPH_USART3
#define PMU2_UART      USART3
#define PMU2_SPEED     9600
#define PMU2_AF        LL_GPIO_AF_1

#define PMU3_PINS_PORT GPIOC
#define PMU3_RX_PIN    LL_GPIO_PIN_1
#define PMU3_TX_PIN    LL_GPIO_PIN_0
#define PMU3_PINS_CLOCK    LL_AHB1_GRP1_PERIPH_GPIOC
#define PMU3_UART_CLOCK    LL_APB1_GRP2_PERIPH_USART6
#define PMU3_UART      USART6
#define PMU3_SPEED     9600
#define PMU3_AF        LL_GPIO_AF_2

#define I2C_SLAVE_PINS_PORT  GPIOB
#define I2C_SLAVE_SCL_PIN    LL_GPIO_PIN_8
#define I2C_SLAVE_SDA_PIN    LL_GPIO_PIN_9
#define I2C_SLAVE_PINS_CLOCK LL_AHB1_GRP1_PERIPH_GPIOB
#define I2C_SLAVE_CLOCK      LL_APB1_GRP1_PERIPH_I2C1
#define I2C_SLAVE_AF         LL_GPIO_AF_1
#define I2C_SLAVE            I2C1

#endif /* PINS_H */